permalink: /:year/:month/:title.html
paginate_path: "/page:num"
paginate: 5
excerpt_separator: "<!-- more -->"
theme: minima
# cdn_domain: https://out-man.top
# theme: jekyll-theme-slate
#remote_theme: "jekyll/minima@1e8a445"
plugins:
  - jekyll-paginate
minima:
  show_excerpts: true
  hide_site_feed_link: true
  social_links:
  - title: folk me on GitHub
    icon: github
    url: "https://github.com/xuanyan"