paginate: 5
excerpt_separator: "<!-- more -->"
remote_theme: "jekyll/minima"
plugins:
  - jekyll-paginate
minima:
  show_excerpts: true
  hide_site_feed_link: true
  social_links:
  - title: folk me on GitHub
    icon: github
    url: "https://github.com/xuanyan"
