title: 隔壁宣哥
author:
  name: xuanyan
  email: xuanyan@icloud.com

description: >
  I have no regret in my life! 
  I remember that one day I ran under the setting sun, that's the youth which have already passed.

paginate: 5
excerpt_separator: "<!-- more -->"
remote_theme: "jekyll/minima"
plugins:
  - jekyll-paginate
  - jekyll-feed
minima:
  show_excerpts: true
  hide_site_feed_link: true
  social_links:
  - title: folk me on GitHub
    icon: github
    url: "https://github.com/xuanyan"
